# Generated by Django 3.0.14 on 2021-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='writer',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Presented'), (1, 'Accepted'), (2, 'Denied'), (3, 'Revision'), (4, 'Pending images'), (5, 'Images accepted'), (6, 'Images denied'), (7, 'Pending layout'), (8, 'Layout accepted'), (9, 'Layout denied'), (10, 'Translate'), (11, 'Published')], default=0),
        ),
    ]
