# Generated by Django 3.0.14 on 2021-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0002_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='escrip', to='eBook.Book'),
        ),
    ]
